spring.application.name=app-web-alumnos

# Render asigna el puerto en $PORT
server.port=${PORT:8080}

# Datasource tomado de variables de entorno
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
